// cities.js — Daftar kota/kabupaten Indonesia untuk kalkulasi ongkir
// is_dki: true = DKI Jakarta (J&T Reguler Rp10.000/kg)
// is_dki: false = Luar DKI (Lion Parcel Rp20.000/kg)

const CITIES = [
  // ─── DKI JAKARTA ──────────────────────────────────────────────────────────
  { name: "Jakarta Pusat", is_dki: true },
  { name: "Jakarta Utara", is_dki: true },
  { name: "Jakarta Barat", is_dki: true },
  { name: "Jakarta Selatan", is_dki: true },
  { name: "Jakarta Timur", is_dki: true },
  { name: "Kepulauan Seribu", is_dki: true },

  // ─── BANTEN ───────────────────────────────────────────────────────────────
  { name: "Tangerang", is_dki: false },
  { name: "Tangerang Selatan", is_dki: false },
  { name: "Kabupaten Tangerang", is_dki: false },
  { name: "Serang", is_dki: false },
  { name: "Kabupaten Serang", is_dki: false },
  { name: "Cilegon", is_dki: false },
  { name: "Lebak", is_dki: false },
  { name: "Pandeglang", is_dki: false },

  // ─── JAWA BARAT ───────────────────────────────────────────────────────────
  { name: "Bekasi", is_dki: false },
  { name: "Kabupaten Bekasi", is_dki: false },
  { name: "Depok", is_dki: false },
  { name: "Bogor", is_dki: false },
  { name: "Kabupaten Bogor", is_dki: false },
  { name: "Bandung", is_dki: false },
  { name: "Kabupaten Bandung", is_dki: false },
  { name: "Bandung Barat", is_dki: false },
  { name: "Cimahi", is_dki: false },
  { name: "Cirebon", is_dki: false },
  { name: "Kabupaten Cirebon", is_dki: false },
  { name: "Karawang", is_dki: false },
  { name: "Subang", is_dki: false },
  { name: "Purwakarta", is_dki: false },
  { name: "Sukabumi", is_dki: false },
  { name: "Kabupaten Sukabumi", is_dki: false },
  { name: "Cianjur", is_dki: false },
  { name: "Garut", is_dki: false },
  { name: "Tasikmalaya", is_dki: false },
  { name: "Kabupaten Tasikmalaya", is_dki: false },
  { name: "Ciamis", is_dki: false },
  { name: "Kuningan", is_dki: false },
  { name: "Majalengka", is_dki: false },
  { name: "Sumedang", is_dki: false },
  { name: "Indramayu", is_dki: false },
  { name: "Pangandaran", is_dki: false },
  { name: "Banjar", is_dki: false },

  // ─── JAWA TENGAH ──────────────────────────────────────────────────────────
  { name: "Semarang", is_dki: false },
  { name: "Kabupaten Semarang", is_dki: false },
  { name: "Solo (Surakarta)", is_dki: false },
  { name: "Yogyakarta", is_dki: false },
  { name: "Magelang", is_dki: false },
  { name: "Kabupaten Magelang", is_dki: false },
  { name: "Purwokerto (Banyumas)", is_dki: false },
  { name: "Cilacap", is_dki: false },
  { name: "Kebumen", is_dki: false },
  { name: "Purworejo", is_dki: false },
  { name: "Klaten", is_dki: false },
  { name: "Boyolali", is_dki: false },
  { name: "Sukoharjo", is_dki: false },
  { name: "Wonogiri", is_dki: false },
  { name: "Karanganyar", is_dki: false },
  { name: "Sragen", is_dki: false },
  { name: "Grobogan", is_dki: false },
  { name: "Blora", is_dki: false },
  { name: "Rembang", is_dki: false },
  { name: "Pati", is_dki: false },
  { name: "Kudus", is_dki: false },
  { name: "Jepara", is_dki: false },
  { name: "Demak", is_dki: false },
  { name: "Kendal", is_dki: false },
  { name: "Batang", is_dki: false },
  { name: "Pekalongan", is_dki: false },
  { name: "Kabupaten Pekalongan", is_dki: false },
  { name: "Pemalang", is_dki: false },
  { name: "Tegal", is_dki: false },
  { name: "Kabupaten Tegal", is_dki: false },
  { name: "Brebes", is_dki: false },
  { name: "Wonosobo", is_dki: false },
  { name: "Temanggung", is_dki: false },
  { name: "Salatiga", is_dki: false },

  // ─── DI YOGYAKARTA ────────────────────────────────────────────────────────
  { name: "Sleman", is_dki: false },
  { name: "Bantul", is_dki: false },
  { name: "Gunung Kidul", is_dki: false },
  { name: "Kulon Progo", is_dki: false },

  // ─── JAWA TIMUR ───────────────────────────────────────────────────────────
  { name: "Surabaya", is_dki: false },
  { name: "Malang", is_dki: false },
  { name: "Kabupaten Malang", is_dki: false },
  { name: "Batu", is_dki: false },
  { name: "Sidoarjo", is_dki: false },
  { name: "Gresik", is_dki: false },
  { name: "Mojokerto", is_dki: false },
  { name: "Kabupaten Mojokerto", is_dki: false },
  { name: "Jombang", is_dki: false },
  { name: "Kediri", is_dki: false },
  { name: "Kabupaten Kediri", is_dki: false },
  { name: "Blitar", is_dki: false },
  { name: "Kabupaten Blitar", is_dki: false },
  { name: "Tulungagung", is_dki: false },
  { name: "Trenggalek", is_dki: false },
  { name: "Nganjuk", is_dki: false },
  { name: "Madiun", is_dki: false },
  { name: "Kabupaten Madiun", is_dki: false },
  { name: "Magetan", is_dki: false },
  { name: "Ngawi", is_dki: false },
  { name: "Bojonegoro", is_dki: false },
  { name: "Tuban", is_dki: false },
  { name: "Lamongan", is_dki: false },
  { name: "Bangkalan", is_dki: false },
  { name: "Sampang", is_dki: false },
  { name: "Pamekasan", is_dki: false },
  { name: "Sumenep", is_dki: false },
  { name: "Pasuruan", is_dki: false },
  { name: "Kabupaten Pasuruan", is_dki: false },
  { name: "Probolinggo", is_dki: false },
  { name: "Kabupaten Probolinggo", is_dki: false },
  { name: "Lumajang", is_dki: false },
  { name: "Jember", is_dki: false },
  { name: "Bondowoso", is_dki: false },
  { name: "Situbondo", is_dki: false },
  { name: "Banyuwangi", is_dki: false },
  { name: "Ponorogo", is_dki: false },
  { name: "Pacitan", is_dki: false },

  // ─── BALI ─────────────────────────────────────────────────────────────────
  { name: "Denpasar", is_dki: false },
  { name: "Badung", is_dki: false },
  { name: "Gianyar", is_dki: false },
  { name: "Tabanan", is_dki: false },
  { name: "Bangli", is_dki: false },
  { name: "Klungkung", is_dki: false },
  { name: "Karangasem", is_dki: false },
  { name: "Buleleng", is_dki: false },
  { name: "Jembrana", is_dki: false },

  // ─── NUSA TENGGARA BARAT ──────────────────────────────────────────────────
  { name: "Mataram", is_dki: false },
  { name: "Lombok Barat", is_dki: false },
  { name: "Lombok Tengah", is_dki: false },
  { name: "Lombok Timur", is_dki: false },
  { name: "Lombok Utara", is_dki: false },
  { name: "Sumbawa", is_dki: false },
  { name: "Sumbawa Barat", is_dki: false },
  { name: "Dompu", is_dki: false },
  { name: "Bima", is_dki: false },
  { name: "Kabupaten Bima", is_dki: false },

  // ─── NUSA TENGGARA TIMUR ──────────────────────────────────────────────────
  { name: "Kupang", is_dki: false },
  { name: "Kabupaten Kupang", is_dki: false },
  { name: "Ende", is_dki: false },
  { name: "Flores Timur", is_dki: false },
  { name: "Manggarai", is_dki: false },
  { name: "Manggarai Barat", is_dki: false },
  { name: "Sikka", is_dki: false },
  { name: "Sumba Barat", is_dki: false },
  { name: "Sumba Timur", is_dki: false },
  { name: "Timor Tengah Selatan", is_dki: false },
  { name: "Timor Tengah Utara", is_dki: false },

  // ─── KALIMANTAN BARAT ─────────────────────────────────────────────────────
  { name: "Pontianak", is_dki: false },
  { name: "Kabupaten Pontianak", is_dki: false },
  { name: "Singkawang", is_dki: false },
  { name: "Sambas", is_dki: false },
  { name: "Sanggau", is_dki: false },
  { name: "Sintang", is_dki: false },
  { name: "Ketapang", is_dki: false },
  { name: "Mempawah", is_dki: false },

  // ─── KALIMANTAN TENGAH ────────────────────────────────────────────────────
  { name: "Palangkaraya", is_dki: false },
  { name: "Kotawaringin Barat", is_dki: false },
  { name: "Kotawaringin Timur", is_dki: false },
  { name: "Kapuas", is_dki: false },
  { name: "Barito Selatan", is_dki: false },
  { name: "Barito Utara", is_dki: false },

  // ─── KALIMANTAN SELATAN ───────────────────────────────────────────────────
  { name: "Banjarmasin", is_dki: false },
  { name: "Banjarbaru", is_dki: false },
  { name: "Kabupaten Banjar", is_dki: false },
  { name: "Barito Kuala", is_dki: false },
  { name: "Hulu Sungai Selatan", is_dki: false },
  { name: "Hulu Sungai Tengah", is_dki: false },
  { name: "Hulu Sungai Utara", is_dki: false },
  { name: "Tabalong", is_dki: false },
  { name: "Tapin", is_dki: false },

  // ─── KALIMANTAN TIMUR ─────────────────────────────────────────────────────
  { name: "Samarinda", is_dki: false },
  { name: "Balikpapan", is_dki: false },
  { name: "Bontang", is_dki: false },
  { name: "Kutai Kartanegara", is_dki: false },
  { name: "Kutai Barat", is_dki: false },
  { name: "Kutai Timur", is_dki: false },
  { name: "Berau", is_dki: false },
  { name: "Penajam Paser Utara", is_dki: false },
  { name: "Paser", is_dki: false },
  { name: "Mahakam Ulu", is_dki: false },

  // ─── KALIMANTAN UTARA ─────────────────────────────────────────────────────
  { name: "Tarakan", is_dki: false },
  { name: "Nunukan", is_dki: false },
  { name: "Bulungan", is_dki: false },
  { name: "Malinau", is_dki: false },
  { name: "Tana Tidung", is_dki: false },

  // ─── SULAWESI SELATAN ─────────────────────────────────────────────────────
  { name: "Makassar", is_dki: false },
  { name: "Parepare", is_dki: false },
  { name: "Palopo", is_dki: false },
  { name: "Gowa", is_dki: false },
  { name: "Maros", is_dki: false },
  { name: "Pangkajene", is_dki: false },
  { name: "Barru", is_dki: false },
  { name: "Bone", is_dki: false },
  { name: "Soppeng", is_dki: false },
  { name: "Wajo", is_dki: false },
  { name: "Sidrap", is_dki: false },
  { name: "Pinrang", is_dki: false },
  { name: "Enrekang", is_dki: false },
  { name: "Luwu", is_dki: false },
  { name: "Luwu Utara", is_dki: false },
  { name: "Luwu Timur", is_dki: false },
  { name: "Bantaeng", is_dki: false },
  { name: "Jeneponto", is_dki: false },
  { name: "Takalar", is_dki: false },
  { name: "Selayar", is_dki: false },
  { name: "Bulukumba", is_dki: false },
  { name: "Sinjai", is_dki: false },

  // ─── SULAWESI TENGAH ──────────────────────────────────────────────────────
  { name: "Palu", is_dki: false },
  { name: "Donggala", is_dki: false },
  { name: "Parigi Moutong", is_dki: false },
  { name: "Poso", is_dki: false },
  { name: "Morowali", is_dki: false },
  { name: "Tojo Una-Una", is_dki: false },
  { name: "Banggai", is_dki: false },
  { name: "Sigi", is_dki: false },

  // ─── SULAWESI TENGGARA ────────────────────────────────────────────────────
  { name: "Kendari", is_dki: false },
  { name: "Bau-Bau", is_dki: false },
  { name: "Kolaka", is_dki: false },
  { name: "Konawe", is_dki: false },
  { name: "Muna", is_dki: false },
  { name: "Buton", is_dki: false },
  { name: "Wakatobi", is_dki: false },

  // ─── SULAWESI UTARA ───────────────────────────────────────────────────────
  { name: "Manado", is_dki: false },
  { name: "Bitung", is_dki: false },
  { name: "Tomohon", is_dki: false },
  { name: "Kotamobagu", is_dki: false },
  { name: "Minahasa", is_dki: false },
  { name: "Minahasa Utara", is_dki: false },
  { name: "Minahasa Selatan", is_dki: false },
  { name: "Bolaang Mongondow", is_dki: false },
  { name: "Kepulauan Sangihe", is_dki: false },
  { name: "Kepulauan Talaud", is_dki: false },

  // ─── GORONTALO ────────────────────────────────────────────────────────────
  { name: "Gorontalo", is_dki: false },
  { name: "Kabupaten Gorontalo", is_dki: false },
  { name: "Pohuwato", is_dki: false },
  { name: "Bone Bolango", is_dki: false },

  // ─── SULAWESI BARAT ───────────────────────────────────────────────────────
  { name: "Mamuju", is_dki: false },
  { name: "Mamasa", is_dki: false },
  { name: "Polewali Mandar", is_dki: false },
  { name: "Pasangkayu", is_dki: false },

  // ─── SUMATERA UTARA ───────────────────────────────────────────────────────
  { name: "Medan", is_dki: false },
  { name: "Binjai", is_dki: false },
  { name: "Pematangsiantar", is_dki: false },
  { name: "Tebing Tinggi", is_dki: false },
  { name: "Tanjungbalai", is_dki: false },
  { name: "Sibolga", is_dki: false },
  { name: "Padangsidimpuan", is_dki: false },
  { name: "Gunungsitoli", is_dki: false },
  { name: "Deli Serdang", is_dki: false },
  { name: "Langkat", is_dki: false },
  { name: "Karo", is_dki: false },
  { name: "Simalungun", is_dki: false },
  { name: "Asahan", is_dki: false },
  { name: "Labuhanbatu", is_dki: false },
  { name: "Tapanuli Utara", is_dki: false },
  { name: "Tapanuli Tengah", is_dki: false },
  { name: "Tapanuli Selatan", is_dki: false },
  { name: "Nias", is_dki: false },

  // ─── SUMATERA BARAT ───────────────────────────────────────────────────────
  { name: "Padang", is_dki: false },
  { name: "Bukittinggi", is_dki: false },
  { name: "Payakumbuh", is_dki: false },
  { name: "Pariaman", is_dki: false },
  { name: "Solok", is_dki: false },
  { name: "Sawahlunto", is_dki: false },
  { name: "Padang Panjang", is_dki: false },
  { name: "Agam", is_dki: false },
  { name: "Pesisir Selatan", is_dki: false },
  { name: "Tanah Datar", is_dki: false },
  { name: "Mentawai", is_dki: false },

  // ─── RIAU ─────────────────────────────────────────────────────────────────
  { name: "Pekanbaru", is_dki: false },
  { name: "Dumai", is_dki: false },
  { name: "Kampar", is_dki: false },
  { name: "Bengkalis", is_dki: false },
  { name: "Siak", is_dki: false },
  { name: "Rokan Hulu", is_dki: false },
  { name: "Rokan Hilir", is_dki: false },
  { name: "Indragiri Hulu", is_dki: false },
  { name: "Indragiri Hilir", is_dki: false },
  { name: "Kepulauan Meranti", is_dki: false },
  { name: "Pelalawan", is_dki: false },
  { name: "Kuantan Singingi", is_dki: false },

  // ─── KEPULAUAN RIAU ───────────────────────────────────────────────────────
  { name: "Batam", is_dki: false },
  { name: "Tanjungpinang", is_dki: false },
  { name: "Bintan", is_dki: false },
  { name: "Karimun", is_dki: false },
  { name: "Natuna", is_dki: false },
  { name: "Lingga", is_dki: false },
  { name: "Kepulauan Anambas", is_dki: false },

  // ─── JAMBI ────────────────────────────────────────────────────────────────
  { name: "Jambi", is_dki: false },
  { name: "Sungai Penuh", is_dki: false },
  { name: "Batanghari", is_dki: false },
  { name: "Bungo", is_dki: false },
  { name: "Kerinci", is_dki: false },
  { name: "Merangin", is_dki: false },
  { name: "Muaro Jambi", is_dki: false },
  { name: "Sarolangun", is_dki: false },
  { name: "Tanjung Jabung Barat", is_dki: false },
  { name: "Tanjung Jabung Timur", is_dki: false },
  { name: "Tebo", is_dki: false },

  // ─── SUMATERA SELATAN ─────────────────────────────────────────────────────
  { name: "Palembang", is_dki: false },
  { name: "Prabumulih", is_dki: false },
  { name: "Pagar Alam", is_dki: false },
  { name: "Lubuklinggau", is_dki: false },
  { name: "Banyuasin", is_dki: false },
  { name: "Lahat", is_dki: false },
  { name: "Muara Enim", is_dki: false },
  { name: "Musi Banyuasin", is_dki: false },
  { name: "Musi Rawas", is_dki: false },
  { name: "Ogan Komering Ilir", is_dki: false },
  { name: "Ogan Komering Ulu", is_dki: false },
  { name: "Empat Lawang", is_dki: false },

  // ─── BANGKA BELITUNG ──────────────────────────────────────────────────────
  { name: "Pangkalpinang", is_dki: false },
  { name: "Bangka", is_dki: false },
  { name: "Belitung", is_dki: false },
  { name: "Bangka Barat", is_dki: false },
  { name: "Bangka Tengah", is_dki: false },
  { name: "Bangka Selatan", is_dki: false },
  { name: "Belitung Timur", is_dki: false },

  // ─── BENGKULU ─────────────────────────────────────────────────────────────
  { name: "Bengkulu", is_dki: false },
  { name: "Rejang Lebong", is_dki: false },
  { name: "Bengkulu Selatan", is_dki: false },
  { name: "Bengkulu Utara", is_dki: false },
  { name: "Kepahiang", is_dki: false },
  { name: "Lebong", is_dki: false },
  { name: "Mukomuko", is_dki: false },
  { name: "Seluma", is_dki: false },
  { name: "Kaur", is_dki: false },

  // ─── LAMPUNG ──────────────────────────────────────────────────────────────
  { name: "Bandar Lampung", is_dki: false },
  { name: "Metro", is_dki: false },
  { name: "Lampung Barat", is_dki: false },
  { name: "Lampung Selatan", is_dki: false },
  { name: "Lampung Tengah", is_dki: false },
  { name: "Lampung Timur", is_dki: false },
  { name: "Lampung Utara", is_dki: false },
  { name: "Mesuji", is_dki: false },
  { name: "Pesawaran", is_dki: false },
  { name: "Pesisir Barat", is_dki: false },
  { name: "Pringsewu", is_dki: false },
  { name: "Tanggamus", is_dki: false },
  { name: "Tulang Bawang", is_dki: false },
  { name: "Way Kanan", is_dki: false },

  // ─── ACEH ─────────────────────────────────────────────────────────────────
  { name: "Banda Aceh", is_dki: false },
  { name: "Sabang", is_dki: false },
  { name: "Langsa", is_dki: false },
  { name: "Lhokseumawe", is_dki: false },
  { name: "Subulussalam", is_dki: false },
  { name: "Aceh Besar", is_dki: false },
  { name: "Aceh Barat", is_dki: false },
  { name: "Aceh Selatan", is_dki: false },
  { name: "Aceh Timur", is_dki: false },
  { name: "Aceh Tengah", is_dki: false },
  { name: "Aceh Utara", is_dki: false },
  { name: "Pidie", is_dki: false },
  { name: "Bireuen", is_dki: false },
  { name: "Simeulue", is_dki: false },
  { name: "Gayo Lues", is_dki: false },
  { name: "Nagan Raya", is_dki: false },

  // ─── MALUKU ───────────────────────────────────────────────────────────────
  { name: "Ambon", is_dki: false },
  { name: "Tual", is_dki: false },
  { name: "Maluku Tengah", is_dki: false },
  { name: "Maluku Tenggara", is_dki: false },
  { name: "Buru", is_dki: false },
  { name: "Seram Bagian Barat", is_dki: false },
  { name: "Seram Bagian Timur", is_dki: false },
  { name: "Kepulauan Aru", is_dki: false },
  { name: "Maluku Barat Daya", is_dki: false },
  { name: "Kepulauan Tanimbar", is_dki: false },

  // ─── MALUKU UTARA ─────────────────────────────────────────────────────────
  { name: "Ternate", is_dki: false },
  { name: "Tidore Kepulauan", is_dki: false },
  { name: "Halmahera Barat", is_dki: false },
  { name: "Halmahera Tengah", is_dki: false },
  { name: "Halmahera Timur", is_dki: false },
  { name: "Halmahera Selatan", is_dki: false },
  { name: "Halmahera Utara", is_dki: false },
  { name: "Kepulauan Sula", is_dki: false },
  { name: "Pulau Taliabu", is_dki: false },

  // ─── PAPUA ────────────────────────────────────────────────────────────────
  { name: "Jayapura", is_dki: false },
  { name: "Merauke", is_dki: false },
  { name: "Nabire", is_dki: false },
  { name: "Sorong", is_dki: false },
  { name: "Manokwari", is_dki: false },
  { name: "Biak Numfor", is_dki: false },
  { name: "Fakfak", is_dki: false },
  { name: "Timika (Mimika)", is_dki: false },
  { name: "Wamena (Jayawijaya)", is_dki: false },
  { name: "Sarmi", is_dki: false },
  { name: "Raja Ampat", is_dki: false },
  { name: "Teluk Bintuni", is_dki: false },
  { name: "Teluk Wondama", is_dki: false },
  { name: "Kaimana", is_dki: false },
  { name: "Maybrat", is_dki: false },
  { name: "Tambrauw", is_dki: false },
  { name: "Pegunungan Bintang", is_dki: false },
  { name: "Yahukimo", is_dki: false },
  { name: "Puncak Jaya", is_dki: false },
  { name: "Yalimo", is_dki: false },
  { name: "Lanny Jaya", is_dki: false },
  { name: "Mappi", is_dki: false },
  { name: "Asmat", is_dki: false },
  { name: "Boven Digoel", is_dki: false },
];

// Sorting: DKI first, then alphabetical
CITIES.sort((a, b) => {
  if (a.is_dki !== b.is_dki) return b.is_dki - a.is_dki;
  return a.name.localeCompare(b.name, 'id');
});

module.exports = { CITIES };
